import './core/bootstrap/tz';
import { bootstrapLogger } from './infrastructure/observability/logger/logger.bootstrap';
import { runMigrations } from './persistence/migrations/run-migrations/run-migrations';

/**
 * The `migrate` CLI: run by the compose service before the backend starts, and by
 * `pnpm db:migrate` locally.
 *
 * Migration files are generated by `pnpm db:generate` from the schema and reviewed;
 * they are never written by hand, and `drizzle-kit push` is never used — it changes
 * the schema with no file a reviewer could read.
 */

const logger = bootstrapLogger.child({ name: 'Migrations' });

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  logger.fatal('DATABASE_URL is not set');
  process.exit(1);
}

// Exit explicitly: a one-shot CLI must not bet on every library releasing every
// handle, or the container that runs it never finishes and the stack never starts.
runMigrations({ databaseUrl, migrationsFolder: './drizzle', logger })
  .then(() => {
    logger.flush();
    setImmediate(() => process.exit(0));
  })
  .catch((err: unknown) => {
    logger.fatal({ err }, 'Migration failed');
    logger.flush();
    process.exit(1);
  });
