import './core/bootstrap/tz';
import { existsSync } from 'node:fs';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { Pool } from 'pg';
import { bootstrapLogger } from './infrastructure/observability/logger/logger.bootstrap';

/**
 * Applies the generated migrations in `./drizzle`, creating the database first if
 * it does not exist. A one-shot CLI: run by the `migrate` compose service before
 * the backend starts, and by `pnpm db:migrate` locally.
 *
 * Migration files are generated by `pnpm db:generate` from the schema and reviewed;
 * they are never written by hand, and `drizzle-kit push` is never used — it changes
 * the schema with no file a reviewer could read.
 */

const logger = bootstrapLogger.child({ name: 'Migrations' });

const MIGRATIONS_FOLDER = './drizzle';
/** `pg` waits forever by default; an unreachable database must fail, not hang. */
const CONNECT_TIMEOUT_MS = 15_000;

function requireDatabaseUrl(): string {
  const url = process.env.DATABASE_URL;
  if (!url) {
    logger.fatal('DATABASE_URL is not set');
    process.exit(1);
  }
  return url;
}

async function ensureDatabaseExists(databaseUrl: string): Promise<void> {
  const target = new URL(databaseUrl);
  const databaseName = decodeURIComponent(target.pathname.replace(/^\//, ''));
  if (!databaseName || databaseName === 'postgres') return;

  const admin = new URL(databaseUrl);
  admin.pathname = '/postgres';
  const pool = new Pool({
    connectionString: admin.toString(),
    connectionTimeoutMillis: CONNECT_TIMEOUT_MS,
  });
  try {
    const { rowCount } = await pool.query(
      'SELECT 1 FROM pg_database WHERE datname = $1',
      [databaseName],
    );
    if (rowCount === 0) {
      // Identifiers cannot be bound as parameters; the name comes from our own env.
      await pool.query(`CREATE DATABASE "${databaseName.replace(/"/g, '""')}"`);
      logger.info({ databaseName }, 'Database created');
    }
  } finally {
    await pool.end();
  }
}

async function run(): Promise<void> {
  const databaseUrl = requireDatabaseUrl();
  await ensureDatabaseExists(databaseUrl);

  if (!existsSync(`${MIGRATIONS_FOLDER}/meta/_journal.json`)) {
    logger.info('No migrations generated yet — nothing to apply');
    return;
  }

  const pool = new Pool({
    connectionString: databaseUrl,
    connectionTimeoutMillis: CONNECT_TIMEOUT_MS,
  });
  try {
    await migrate(drizzle(pool), { migrationsFolder: MIGRATIONS_FOLDER });
    logger.info('Migrations applied');
  } finally {
    await pool.end();
  }
}

// Exit explicitly: a one-shot CLI must not bet on every library releasing every
// handle, or the container that runs it never finishes and the stack never starts.
run()
  .then(() => {
    logger.flush();
    setImmediate(() => process.exit(0));
  })
  .catch((err: unknown) => {
    logger.fatal({ err }, 'Migration failed');
    logger.flush();
    process.exit(1);
  });
